# Generated by Django 3.1.7 on 2021-04-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210408_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follows',
            new_name='follow',
        ),
    ]
